const { saveAs } = require("file-saver");
const XLSX = require("xlsx");
const parser = require("./parser");

function download(filename, text) {
    const aoa = parser(text);

    if (!aoa){
        alert("Некорректный текст");
        return;
    }

    const wb = XLSX.utils.book_new();
    wb.Props = {
        Title: "Generated by Parser IO",
        Subject: "Parser IO",
        Author: "Raz1el",
        CreatedDate: new Date()
    };

    wb.SheetNames.push("Document");
    const ws = XLSX.utils.aoa_to_sheet(aoa);
    wb.Sheets["Document"] = ws;

    const wbout = XLSX.write(wb, {bookType:"xlsx", bookSST: false, type: "array"}); 
    saveAs(new Blob([wbout],{type:"application/octet-stream"}), filename);
}

// Start file download.
document.querySelector("#dwn-btn")
    .addEventListener("click", () => {
        // Generate download of hello.txt file with some content
        const text = document.querySelector("#text-val").value;
        download(new Date().toDateString() + ".xlsx", text);   
    }, false);